Jazzy対応
rt-net/crane_x7_description pull request #10
Opened 2024-12-26 01:52 UTC by Kuwamai

# What does this implement/fix?

Jazzy対応します

# Does this close any currently open issues?

しません

# How has this been tested?

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2025-01-06 08:11 UTC, YusukeKato commented
Ubuntu 24.04 LTS + ROS 2 Jazzy環境で`display.launch.py`を実行してモデルが表示されることを確認しました。

2025-01-06 08:53 UTC, YusukeKato requested changes
一点だけコメントしましたので確認をお願いたします。
それ以外は修正内容よいと思います。

2025-01-06 08:53 UTC, YusukeKato commented on package.xml
> +  <author email="mizoguchi@rt-net.jp">Nozomi Mizoguchi</author>
authorに @Kuwamai さんも追加するとよさそうです。

2025-01-06 10:43 UTC, Kuwamai commented on package.xml
> +  <author email="mizoguchi@rt-net.jp">Nozomi Mizoguchi</author>
ありがとうございます。
追加しました。

2025-01-07 02:52 UTC, YusukeKato approved these changes
LGTMです！

2025-01-07 02:52 UTC, merged