RealSense D435搭載モデルに対応
rt-net/crane_x7_description pull request #5
Opened 2022-11-10 09:53 UTC by Kuwamai

# What does this implement/fix?

RealSense D435搭載モデルに対応するためcamera_linkを追加しました。
xacroを読み込む引数にuse_d435を追加し、launch実行時に`use_d435:=true`を追加することで標準モデルとD435搭載モデルを切り替えることができるようになっています。

# Does this close any currently open issues?

しません

# How has this been tested?

下記コマンドを実行して手先にRealSense D435が表示されることを確認しました。
```
ros2 launch crane_x7_description display.launch.py use_d435:=true
```
# Any other comments?

Gazeboによるカメラのシミュレーションはframe_idの設定がCitadelではできないため実装していません。Gazebo Sensors 6.2.0以降で対応しています。
参考: https://github.com/gazebosim/gz-sensors/blob/gz-sensors7/Changelog.md

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2022-11-11 02:12 UTC, ShotaAk requested changes
動作確認しました。
コメントの確認お願いします。

2022-11-11 02:12 UTC, ShotaAk commented on README.en.md
> +If you use a [RealSense D435 mounter](https://github.com/rt-net/crane_x7_Hardware/blob/master/3d_print_parts/v1.0/CRANE-X7_HandA_RealSenseD435%E3%83%9E%E3%82%A6%E3%83%B3%E3%82%BF.stl), execute the fo
```suggestion
If you use a [RealSense D435 mounter](https://github.com/rt-net/crane_x7_Hardware/blob/master/3d_print_parts/v1.0/CRANE-X7_HandA_RealSenseD435マウンタ.stl), execute the following command.
```

2022-11-11 02:12 UTC, ShotaAk commented on README.md
> +[RealSense D435マウンタ](https://github.com/rt-net/crane_x7_Hardware/blob/master/3d_print_parts/v1.0/CRANE-X7_HandA_RealSenseD435%E3%83%9E%E3%82%A6%E3%83%B3%E3%82%BF.stl)を使用している場合は次のコマンドを実行してください。
```suggestion
[RealSense D435マウンタ](https://github.com/rt-net/crane_x7_Hardware/blob/master/3d_print_parts/v1.0/CRANE-X7_HandA_RealSenseD435マウンタ.stl)を使用している場合は次のコマンドを実行してください。
```

2022-11-11 02:12 UTC, ShotaAk commented on README.en.md
> +
今あるdisplay_launch.pngの位置は変更せず、

新たにD435を取り付けた画像を貼ってほしいです。

例：
![image](https://user-images.githubusercontent.com/18494952/201076911-7da5b90b-38fe-4dc3-b621-7560fecf72cc.png)

2022-11-11 02:12 UTC, ShotaAk commented on README.md
> +```
今あるdisplay_launch.pngの位置は変更せず、

新たにD435を取り付けた画像を貼ってほしいです。

2022-11-11 02:12 UTC, ShotaAk commented on crane_x7_description/robot_description_loader.py
> +        self.use_d435 = 'false'
use_d435フラグが機能することを確認するため、ユニットテストを追加してください。

https://github.com/rt-net/crane_x7_description/blob/ros2/test/test_robot_description_loader.py

2022-11-11 02:12 UTC, ShotaAk commented on launch/display.launch.py
> +        description='Use d435.'
変更案です。
```suggestion
        description='Set true to attach the RealSense D435 model.'
```

2022-11-11 02:12 UTC, ShotaAk commented on urdf/crane_x7.gazebo.xacro
> -
不要な変更なので、取り消してください。

2022-11-11 02:12 UTC, ShotaAk commented on urdf/crane_x7.xacro
> +    </xacro:if>
realsense2_cameraの_d435.urdf.xacroにある、sensor_d435マクロを使えば、
自作マクロは不要になります。

置き換えできるか検討お願いします。

2022-11-11 08:48 UTC, Kuwamai commented on urdf/crane_x7.xacro
> +    </xacro:if>
置き換えました。

2022-11-15 02:40 UTC, ShotaAk approved these changes
LGTM

2022-11-15 04:58 UTC, merged